"""empty message

Revision ID: 5328f076dd7a
Revises: 
Create Date: 2020-01-05 13:05:15.123764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5328f076dd7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocationDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gatewayId', sa.Integer(), nullable=True),
    sa.Column('locationName', sa.String(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gatewayId')
    )
    op.create_table('rfidScanned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('has_transfered', sa.Boolean(), nullable=False),
    sa.Column('entryDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfidScanned')
    op.drop_table('LocationDetails')
    # ### end Alembic commands ###
