"""empty message

Revision ID: 7f70862cdbfe
Revises: ee161454681c
Create Date: 2019-12-26 19:13:05.143862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f70862cdbfe'
down_revision = 'ee161454681c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LocationDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationName', sa.String(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locationName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LocationDetails')
    # ### end Alembic commands ###
